name: Build Release and Staging - Signed APK and AAB

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - uses: actions/checkout@v2

      - name: Run Tests
        run: ./gradlew test

      - name: Decode Keystore file
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'keystore/MyTasks.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Make ./gradlew executable
        run: chmod +x ./gradlew

      - name: Build Signed AAB
        run: ./gradlew androidApp:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      - name: Upload Signed AAB
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: androidApp/build/outputs/bundle/release

      - name: Build Signed APK
        run: ./gradlew androidApp:assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      - name: Upload Signed APK
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: androidApp/build/outputs/apk/release
