name: Build Prod Apk
on:
  push:
    branches:
      - master
      - development
jobs:
  build:
    runs-on: macos-latest
    steps:

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/checkout@v2

      - name: Make ./gradlew executable
        run: chmod +x ./gradlew

      - name: Decode Google Play service account file
        env:
          SERVICE_ACCOUNT_DATA_STRING: ${{ secrets.SERVICE_ACCOUNT_DATA }}
        run: |
          echo $SERVICE_ACCOUNT_DATA_STRING
          echo $SERVICE_ACCOUNT_DATA_STRING | base64 --decode > service_account.json
          ls
#
#      - name: Build APK
#        run: ./gradlew :androidApp:assembleRelease
#
#      - name: Upload APK
#        uses: actions/upload-artifact@v2
#        with:
#          name: APK
#          path: androidApp/build/outputs/apk/release


